version: "3"

services:
  script:
    image: node:14
    working_dir: /work
    volumes: [ .:/work, node-modules:/work/node_modules ]
    stop_signal: SIGKILL
    command:
      - bash
      - -c
      - docker-compose run script redis-server

volumes:
  node-modules:
